// Generated by CoffeeScript 1.3.1
/*
| The purpose of this file is to make it easier for people to check what is assigned to themselves specifically, across all products they are members of.
| Copyright 2012 Andrew Steele on behalf of EPB's A-Team
| Licensed as Public Domain
*/

var api_request, base64str, iterator, make_error_page, make_my_items_page, master_template, master_view_vars, members, partials, password, set_items, user, username;

username = prompt("What e-mail address do you use with Sprint.ly?", "");

password = prompt("What is your Sprint.ly API Key?", "");

make_error_page = function() {
  var page;
  page = $('#view_content');
  return page.empty().html("<h3>You must provide both your e-mail address and API key in order for this bookmarklet to work.</h3>");
};

if ((username != null) && (password != null)) {
  base64str = Base64.encode(username + ":" + password);
  jQuery.ajaxSetup({
    beforeSend: function(xhr) {
      return xhr.setRequestHeader("Authorization", "Basic " + base64str);
    }
  });
} else {
  make_error_page();
}

user = sprintly.proxyData.currentUser;

user.full_name = user.first_name + " " + user.last_name;

user.products = sprintly.proxyData.myProducts;

user.product_length = user.products.length;

user.items = [];

members = sprintly.proxyData.currentUsers;

_.each(members, function(m) {
  return m.full_name = m.first_name + " " + m.last_name;
});

iterator = user.product_length;

api_request = function(path, func) {
  var base, url;
  base = 'https://sprint.ly/api/';
  url = base + path;
  return jQuery.ajax(url, {
    success: function(data) {
      return func(data);
    },
    error: function(xhr, status, error) {
      if (window.console) {
        console.log("Error occurred, status: " + status + " and error: " + error);
      }
      return iterator = iterator - 1;
    }
  });
};

set_items = function(items) {
  var item, p_index, product;
  item = _.first(items);
  product = _.find(user.products, function(p) {
    return p.pk === item.product.id;
  });
  p_index = user.products.indexOf(product);
  items = _.filter(items, function(i) {
    return !i.archived;
  });
  if (p_index) {
    user.products[p_index].items = items;
  }
  iterator = iterator - 1;
  if (iterator === 0) {
    return make_my_items_page();
  }
};

_.each(user.products, function(p_id) {
  return api_request('products/' + product_id + '/items.json', set_items());
});

/*
Types of items:
 40 - Story
 30 - Defect
 20 - Test
 10 - Task
*/


master_view_vars = {
  user_name: user.first_name,
  products: user.products,
  type_number: function() {
    return function(type, render) {
      var typeNum;
      switch (type) {
        case "task":
          typeNum = "10";
          break;
        case "test":
          typeNum = "20";
          break;
        case "defect":
          typeNum = "30";
          break;
        case "story":
          typeNum = "40";
      }
      return typeNum;
    };
  }
};

master_template = "        <h3>All items assigned to you, <strong>{{user_name}}</strong>.</h3>        {{#products}}            <h2><a href='https://sprint.ly/product/{{product.pk}}'>{{product.title}}</a></h2>            {{>sub_items}}        {{/products}}";

partials = {
  sub_items: "        {{#items}}            <div id='item-{{number}}' class='my_item type-{{#type_number}}{{type}}{{/type_number}} status-{{status}}'>                <div class='item_number_and_status'>&hash;{{number}}, status: {{status}}</div>                <div class='item_title'>{{title}}</div>                <div class='item_description'>{{description}}</div>            </div>        {{/items}}        {{^items}}            <p>No items assigned to you for this project.</p>        {{/items}}    "
};

make_my_items_page = function() {
  var new_content, page;
  new_content = Mustache.to_html(master_template, master_view_vars, partials);
  page = $('#view_content');
  return page.empty().html(new_content);
};